version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-nerdstore
        environment:
            RABBITMQ_DEFAULT_USER: "nerdstore"
            RABBITMQ_DEFAULT_PASS: "nerdstore"

    sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: nerdstore-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"     

    web-mvc:
        image: cclautert/nerdstore-distributed-web-mvc-ecommerce:latest
        container_name: nerdstore-distributed-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./web/NSE.WebApp.MVC/Dockerfile
        restart: always            
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://*:5001
        volumes: 
            - dpkeys:/var/data_protection_keys/         
        depends_on:
            - api-catalogo
            - api-identidade
            - api-cliente
            - api-bff-compras

    api-identidade:
        image: cclautert/nerdstore-distributed-api-identidade:latest
        container_name: nerdstore-distributed-api-identidade    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Identidade.API/Dockerfile  
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            
    api-carrinho:
        image: cclautert/nerdstore-distributed-api-carrinho:latest
        container_name: nerdstore-distributed-api-carrinho
        build: 
            context: ../src
            dockerfile: ./services/NSE.Carrinho.API/Dockerfile      
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5201;http://+5202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - sql-server         

    api-catalogo:
        image: cclautert/nerdstore-distributed-api-catalogo:latest
        container_name: nerdstore-distributed-api-catalogo
        build: 
            context: ../src
            dockerfile: ./services/NSE.Catalogo.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5301;http://+5302
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server

    api-cliente:
        image: cclautert/nerdstore-distributed-api-cliente:latest
        container_name: nerdstore-distributed-api-cliente    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Clientes.API/Dockerfile
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - sql-server  

    api-bff-compras:
        image: cclautert/nerdstore-distributed-api-bff-compras:latest
        container_name: nerdstore-distributed-api-bff-compras
        build: 
            context: ../src
            dockerfile: ./api gateways/NSE.Bff.Compras/Dockerfile  
        restart: always 
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - api-carrinho
            - api-pagamento
            - api-pedido
            
    api-pagamento:
        image: cclautert/nerdstore-distributed-api-pagamento:latest
        container_name: nerdstore-distributed-api-pagamento    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Pagamentos.API/Dockerfile
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5601;http://+5602
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - api-pedido
            - sql-server
            
    api-pedido:
        image: cclautert/nerdstore-distributed-api-pedido:latest
        container_name: nerdstore-distributed-api-pedido    
        build: 
            context: ../src
            dockerfile: ./services/NSE.Pedidos.API/Dockerfile 
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5701;http://+5702
            - ASPNETCORE_Kestrel__Certificates__Default__Password=nerdstore
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/nerdstore-certificate.pfx
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            - api-identidade                    

    nerdstore-server:
        image: nginx
        restart: always 
        volumes:
            - ./nginx/nerdstore.conf.conf:/etc/nginx/conf.d/default.conf:ro
            - ./nginx/nerdstore-certificate.key:/etc/nginx/nerdstore-certificate.key:ro
            - ./nginx/nerdstore-certificate.pem:/etc/nginx/nerdstore-certificate.pem:ro
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc

volumes:
    dpkeys:     